"""create creator monitoring tables

Revision ID: 0da7d4157c5f
Revises:
Create Date: 2026-06-04 14:47:45.922494
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0da7d4157c5f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creator_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("platform_account_id", sa.String(length=128), nullable=False),
        sa.Column("nickname", sa.String(length=128), nullable=False),
        sa.Column("profile_url", sa.String(length=500), nullable=False),
        sa.Column("avatar_url", sa.String(length=1000), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("verified_info", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column("group_name", sa.String(length=128), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("monitor_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("monitoring_status", sa.String(length=20), nullable=False),
        sa.Column("follower_count", sa.BigInteger(), nullable=False),
        sa.Column("following_count", sa.BigInteger(), nullable=False),
        sa.Column("total_like_count", sa.BigInteger(), nullable=False),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.Column("last_collected_at", sa.DateTime(), nullable=True),
        sa.Column("next_collect_at", sa.DateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "platform_account_id", name="uq_creator_platform_account"),
    )
    op.create_index(
        op.f("ix_creator_accounts_group_name"), "creator_accounts", ["group_name"], unique=False
    )
    op.create_index(
        op.f("ix_creator_accounts_next_collect_at"),
        "creator_accounts",
        ["next_collect_at"],
        unique=False,
    )
    op.create_index(
        "ix_creator_status_next_collect",
        "creator_accounts",
        ["monitoring_status", "next_collect_at"],
        unique=False,
    )
    op.create_table(
        "collection_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["creator_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_collection_run_creator_started",
        "collection_runs",
        ["creator_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "creator_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("follower_count", sa.BigInteger(), nullable=False),
        sa.Column("following_count", sa.BigInteger(), nullable=False),
        sa.Column("total_like_count", sa.BigInteger(), nullable=False),
        sa.Column("content_count", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["creator_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_creator_snapshot_creator_time",
        "creator_snapshots",
        ["creator_id", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_creator_snapshot_creator_time", table_name="creator_snapshots")
    op.drop_table("creator_snapshots")
    op.drop_index("ix_collection_run_creator_started", table_name="collection_runs")
    op.drop_table("collection_runs")
    op.drop_index("ix_creator_status_next_collect", table_name="creator_accounts")
    op.drop_index(op.f("ix_creator_accounts_next_collect_at"), table_name="creator_accounts")
    op.drop_index(op.f("ix_creator_accounts_group_name"), table_name="creator_accounts")
    op.drop_table("creator_accounts")
    # ### end Alembic commands ###
