"""add content and alert monitoring

Revision ID: 687525cbdc3f
Revises: 0da7d4157c5f
Create Date: 2026-06-04 15:36:35.022064
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "687525cbdc3f"
down_revision: str | None = "0da7d4157c5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("conditions_json", sa.JSON(), nullable=False),
        sa.Column("notification_channels_json", sa.JSON(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alert_rules_alert_type"), "alert_rules", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alert_rules_is_enabled"), "alert_rules", ["is_enabled"], unique=False)
    op.create_table(
        "content_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("platform_content_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("content_url", sa.String(length=1000), nullable=False),
        sa.Column("cover_url", sa.String(length=1000), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("first_discovered_at", sa.DateTime(), nullable=False),
        sa.Column("latest_like_count", sa.BigInteger(), nullable=False),
        sa.Column("latest_comment_count", sa.BigInteger(), nullable=False),
        sa.Column("latest_collect_count", sa.BigInteger(), nullable=False),
        sa.Column("latest_share_count", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("raw_data_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["creator_accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "creator_id", "platform_content_id", name="uq_content_creator_platform_id"
        ),
    )
    op.create_index(
        "ix_content_creator_published",
        "content_posts",
        ["creator_id", "published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_posts_published_at"), "content_posts", ["published_at"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=True),
        sa.Column("rule_id", sa.Integer(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notification_status", sa.String(length=20), nullable=False),
        sa.Column("notification_error", sa.Text(), nullable=True),
        sa.Column("triggered_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["content_id"], ["content_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator_id"], ["creator_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["alert_rules.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_alert_dedupe_key"),
    )
    op.create_index("ix_alert_status_triggered", "alerts", ["status", "triggered_at"], unique=False)
    op.create_index(op.f("ix_alerts_content_id"), "alerts", ["content_id"], unique=False)
    op.create_index(op.f("ix_alerts_creator_id"), "alerts", ["creator_id"], unique=False)
    op.create_index(op.f("ix_alerts_rule_id"), "alerts", ["rule_id"], unique=False)
    op.create_table(
        "content_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.BigInteger(), nullable=False),
        sa.Column("comment_count", sa.BigInteger(), nullable=False),
        sa.Column("collect_count", sa.BigInteger(), nullable=False),
        sa.Column("share_count", sa.BigInteger(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["content_id"], ["content_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_content_snapshot_content_time",
        "content_snapshots",
        ["content_id", "captured_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_content_snapshot_content_time", table_name="content_snapshots")
    op.drop_table("content_snapshots")
    op.drop_index(op.f("ix_alerts_rule_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_creator_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_content_id"), table_name="alerts")
    op.drop_index("ix_alert_status_triggered", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_content_posts_published_at"), table_name="content_posts")
    op.drop_index("ix_content_creator_published", table_name="content_posts")
    op.drop_table("content_posts")
    op.drop_index(op.f("ix_alert_rules_is_enabled"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_alert_type"), table_name="alert_rules")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
